baseURL = 'https://blog.cyberselab.com/' # 线上地址保持不变
#languageCode = 'zh-cn'
#title = '我的 Obsidian 静态博客'
#theme = 'ananke'
#[pagination]
#  pagerSize = 10
# ... 其他配置 ...

# ... 其他配置项

[services]
  [services.googleAnalytics]
    ID = 'G-XXGXCHWTVM'